const UserActionTypes = {
  SIGN_UP: 'SIGN_UP',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  LOG_IN: 'LOG_IN',
  LOG_IN_FAILURE: 'LOG_IN_FAILURE',
  LOG_OUT: 'LOG_OUT',
  JOIN_ORG: 'JOIN_ORG',
  LEAVE_ORG: 'LEAVE_ORG',
  LOAD_USER_PROFILE: 'LOAD_USER_PROFILE',
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',
};

export default UserActionTypes;